#!/bin/bash;
sudo pacman -Sy;
sudo pacman -S --needed --noconfirm reflector;
sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak;
sudo reflector --verbose --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist;
sudo pacman -Sy;
sudo pacman -S --needed --noconfirm git;
sudo pacman -S --needed --noconfirm timeshift;
sudo pacman -S --needed --noconfirm nvidia-dkms;
sudo pacman -S --needed --noconfirm nvidia-utils;
sudo pacman -S --needed --noconfirm lib32-nvidia-utils;
sudo pacman -S --needed --noconfirm nvidia-settings;
sudo pacman -S --needed --noconfirm opencl-nvidia;
sudo pacman -S --needed --noconfirm vulkan-icd-loader;
sudo pacman -S --needed --noconfirm lib32-vulkan-icd-loader;
sudo pacman -S --needed --noconfirm packagekit-qt6;
sudo pacman -S --needed --noconfirm flatpak;
sudo pacman -S --needed --noconfirm fwupd;
sudo pacman -S --needed --noconfirm ffmpegthumbs;
sudo pacman -S --needed --noconfirm unrar;
sudo pacman -S --needed --noconfirm kaccounts-integration;
sudo pacman -S --needed --noconfirm kaccounts-providers;
sudo pacman -S --needed --noconfirm kio-gdrive;
sudo pacman -S --needed --noconfirm kimageformats;
sudo pacman -S --needed --noconfirm amd-ucode;
sudo pacman -S --needed --noconfirm icoutils;
sudo pacman -S --needed --noconfirm libreoffice-fresh;
sudo pacman -S --needed --noconfirm gwenview;
sudo pacman -S --needed --noconfirm spectacle;
sudo pacman -S --needed --noconfirm wine-staging;
sudo pacman -S --needed --noconfirm wine-gecko;
sudo pacman -S --needed --noconfirm wine-mono;
sudo pacman -S --needed --noconfirm lutris;
sudo pacman -S --needed --noconfirm steam;
sudo pacman -S --needed --noconfirm fuse;
sudo pacman -S --needed --noconfirm fuse2;
sudo pacman -S --needed --noconfirm audacity;
sudo pacman -S --needed --noconfirm base-devel;
sudo pacman -S --needed --noconfirm qt5-imageformats;
sudo pacman -S --needed --noconfirm kimageformats;
sudo pacman -S --needed --noconfirm gimp;
sudo pacman -S --needed --noconfirm yt-dlp;
sudo pacman -S --needed --noconfirm exfat-utils;
sudo pacman -S --needed --noconfirm linux-headers;
sudo pacman -S --needed --noconfirm linux-zen-headers;
sudo pacman -S --needed --noconfirm linux-lts-headers;
sudo pacman -S --needed --noconfirm vi;
sudo pacman -S --needed --noconfirm partitionmanager;
sudo pacman -S --needed --noconfirm mangohud;
sudo pacman -S --needed --noconfirm gamemode;
sudo pacman -S --needed --noconfirm qbittorrent;
sudo pacman -S --needed --noconfirm android-udev;
sudo pacman -S --needed --noconfirm chromium;
sudo pacman -S --needed --noconfirm system-config-printer;
sudo pacman -S --needed --noconfirm cups;
sudo pacman -S --needed --noconfirm okular;
sudo pacman -S --needed --noconfirm syncthing;
sudo pacman -S --needed --noconfirm kdeconnect;
sudo pacman -S --needed --noconfirm kcalc;
sudo pacman -S --needed --noconfirm hplip;
sudo pacman -S --needed --noconfirm korganizer;
sudo pacman -S --needed --noconfirm rclone;
sudo pacman -S --needed --noconfirm rsync;
sudo pacman -S --needed --noconfirm sshfs;
sudo pacman -S --needed --noconfirm elisa;
sudo pacman -S --needed --noconfirm ntfs-3g;
sudo systemctl enable --now cronie.service;
sudo systemctl enable --now cups.service;
sudo systemctl enable --now bluetooth;
systemctl --user enable syncthing.service;
git clone https://aur.archlinux.org/yay.git;
cd yay;
makepkg -si;
yay -S --noconfirm pamac-aur;
yay -S --noconfirm libxcrypt-compat;
flatpak install -y flathub net.davidotek.pupgui2;
flatpak install -y flathub com.github.wwmm.easyeffects;
flatpak install -y com.heroicgameslauncher.hgl;
flatpak install -y com.google.Chrome;
flatpak install -y com.microsoft.Edge;
flatpak install -y com.obsproject.Studio;
flatpak install -y com.dec05eba.gpu_screen_recorder;
echo "ALL DONE, reboot";
